package com.example.demo.entity;
// Generated 2019-5-12 16:40:13 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FurnitureHotSaleProductData generated by hbm2java
 */
@Entity
@Table(name="furniture_hot_sale_product_data"
)
public class FurnitureHotSaleProductData  implements java.io.Serializable {


     private String brandId;
     private String brandNm;
     private Integer ratio;

    public FurnitureHotSaleProductData() {
    }

	
    public FurnitureHotSaleProductData(String brandId, String brandNm) {
        this.brandId = brandId;
        this.brandNm = brandNm;
    }
    public FurnitureHotSaleProductData(String brandId, String brandNm, Integer ratio) {
       this.brandId = brandId;
       this.brandNm = brandNm;
       this.ratio = ratio;
    }
   
     @Id 

    
    @Column(name="brand_id", unique=true, nullable=false, length=32)
    public String getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    
    @Column(name="brand_nm", nullable=false, length=32)
    public String getBrandNm() {
        return this.brandNm;
    }
    
    public void setBrandNm(String brandNm) {
        this.brandNm = brandNm;
    }

    
    @Column(name="ratio")
    public Integer getRatio() {
        return this.ratio;
    }
    
    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }




}


