package com.example.demo.entity;
// Generated 2019-5-12 16:40:13 by Hibernate Tools 5.2.5.Final


import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import cn.afterturn.easypoi.excel.annotation.Excel;

/**
 * FurnitureHotSaleTradeData generated by hbm2java
 */
@Entity
@Table(name="furniture_hot_sale_trade_data"
)
public class FurnitureHotSaleTradeData  implements java.io.Serializable {


	 @Excel(name = "种类产品编号(请勿修改)", orderNum = "0")
	 private String saleTradeId;
	 @Excel(name = "种类ID", orderNum = "1")
	 private String typeId;
	 @Excel(name = "种类名", orderNum = "2")
	 private String typeNm;
	 @Excel(name = "产品ID", orderNum = "3")
	 private String productId;
	 @Excel(name = "产品名称", orderNum = "4")
	 private String productNm;
	 @Excel(name = "热销地", orderNum = "5")
	 private String hotSalePlace;
	 @Excel(name = "主要产地", orderNum = "6")
	 private String productPlace;
	 @Excel(name = "年月", orderNum = "7")
	 private String tradeDate;
	 @Excel(name = "交易额", orderNum = "8")
	 private BigDecimal tradeVolume;
	 @Excel(name = "交易额-亚马逊", orderNum = "9")
	 private BigDecimal tradeAmazon;
	 @Excel(name = "交易额-阿里", orderNum = "10")
	 private BigDecimal tradeAli;
	 @Excel(name = "交易额-wish", orderNum = "11")
	 private BigDecimal tradeWish;
	 @Excel(name = "交易额-ebay", orderNum = "12")
	 private BigDecimal tradeEbay;
	 @Excel(name = "交易额-其他", orderNum = "13")
	 private BigDecimal tradeOthers;

    public FurnitureHotSaleTradeData() {
    }

	
    public FurnitureHotSaleTradeData(String saleTradeId, String typeId, String typeNm) {
        this.saleTradeId = saleTradeId;
        this.typeId = typeId;
        this.typeNm = typeNm;
    }
    public FurnitureHotSaleTradeData(String saleTradeId, String typeId, String typeNm, String productId, String productNm, String hotSalePlace, String productPlace, String tradeDate, BigDecimal tradeVolume, BigDecimal tradeAmazon, BigDecimal tradeAli, BigDecimal tradeWish, BigDecimal tradeEbay, BigDecimal tradeOthers) {
       this.saleTradeId = saleTradeId;
       this.typeId = typeId;
       this.typeNm = typeNm;
       this.productId = productId;
       this.productNm = productNm;
       this.hotSalePlace = hotSalePlace;
       this.productPlace = productPlace;
       this.tradeDate = tradeDate;
       this.tradeVolume = tradeVolume;
       this.tradeAmazon = tradeAmazon;
       this.tradeAli = tradeAli;
       this.tradeWish = tradeWish;
       this.tradeEbay = tradeEbay;
       this.tradeOthers = tradeOthers;
    }
   
    @Id
  	@GeneratedValue(generator = "uid")
  	@GenericGenerator(name = "uid", strategy = "uuid")
    @Column(name="sale_trade_id", unique=true, nullable=false, length=64)
    public String getSaleTradeId() {
        return this.saleTradeId;
    }
    
    public void setSaleTradeId(String saleTradeId) {
        this.saleTradeId = saleTradeId;
    }

    
    @Column(name="type_id", nullable=false, length=32)
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    
    @Column(name="type_nm", nullable=false, length=32)
    public String getTypeNm() {
        return this.typeNm;
    }
    
    public void setTypeNm(String typeNm) {
        this.typeNm = typeNm;
    }

    
    @Column(name="product_id", length=32)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="product_nm", length=32)
    public String getProductNm() {
        return this.productNm;
    }
    
    public void setProductNm(String productNm) {
        this.productNm = productNm;
    }

    
    @Column(name="hot_sale_place", length=24)
    public String getHotSalePlace() {
        return this.hotSalePlace;
    }
    
    public void setHotSalePlace(String hotSalePlace) {
        this.hotSalePlace = hotSalePlace;
    }

    
    @Column(name="product_place", length=24)
    public String getProductPlace() {
        return this.productPlace;
    }
    
    public void setProductPlace(String productPlace) {
        this.productPlace = productPlace;
    }

    
    @Column(name="trade_date", length=7)
    public String getTradeDate() {
        return this.tradeDate;
    }
    
    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate;
    }

    
    @Column(name="trade_volume", precision=12)
    public BigDecimal getTradeVolume() {
        return this.tradeVolume;
    }
    
    public void setTradeVolume(BigDecimal tradeVolume) {
        this.tradeVolume = tradeVolume;
    }

    
    @Column(name="trade_amazon", precision=12)
    public BigDecimal getTradeAmazon() {
        return this.tradeAmazon;
    }
    
    public void setTradeAmazon(BigDecimal tradeAmazon) {
        this.tradeAmazon = tradeAmazon;
    }

    
    @Column(name="trade_ali", precision=12)
    public BigDecimal getTradeAli() {
        return this.tradeAli;
    }
    
    public void setTradeAli(BigDecimal tradeAli) {
        this.tradeAli = tradeAli;
    }

    
    @Column(name="trade_wish", precision=12)
    public BigDecimal getTradeWish() {
        return this.tradeWish;
    }
    
    public void setTradeWish(BigDecimal tradeWish) {
        this.tradeWish = tradeWish;
    }

    
    @Column(name="trade_ebay", precision=12)
    public BigDecimal getTradeEbay() {
        return this.tradeEbay;
    }
    
    public void setTradeEbay(BigDecimal tradeEbay) {
        this.tradeEbay = tradeEbay;
    }

    
    @Column(name="trade_others", precision=12)
    public BigDecimal getTradeOthers() {
        return this.tradeOthers;
    }
    
    public void setTradeOthers(BigDecimal tradeOthers) {
        this.tradeOthers = tradeOthers;
    }




}


