package com.example.demo.entity;
// Generated 2019-5-8 8:54:23 by Hibernate Tools 5.2.5.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import cn.afterturn.easypoi.excel.annotation.Excel;

/**
 * GlobalEshopTradeData generated by hbm2java
 */
@Entity
@Table(name="global_eshop_trade_data"
)
public class GlobalEshopTradeData  implements java.io.Serializable {

	 @Excel(name = "交易数据编号(请勿修改)", orderNum = "0")
	 private String tradeId;
	 @Excel(name = "海外仓", orderNum = "1")
	 private String eshopId;
	 @Excel(name = "电商名称", orderNum = "2")
	 private String eshopNm;
	 @Excel(name = "年月", orderNum = "3")
	 private String tradeDate;
	 @Excel(name = "交易额", orderNum = "4")
	 private BigDecimal tradeVolume;
	 @Excel(name = "交易额（发展中国家）", orderNum = "5")
	 private BigDecimal tradeVolumeDeveloped;
	 @Excel(name = "交易额（发达国家）", orderNum = "6")
	 private BigDecimal tradeVolumeDeveloping;
	 @Excel(name = "交易额（亚洲）", orderNum = "7")
	 private BigDecimal tradeVolumeAsia;
	 @Excel(name = "交易额（欧洲）", orderNum = "8")
	 private BigDecimal tradeVolumeEurope;
	 @Excel(name = "交易额（非洲）", orderNum = "9")
	 private BigDecimal tradeVolumeAfrica;
	 @Excel(name = "交易额（大洋洲）", orderNum = "10")
	 private BigDecimal tradeVolumeOceania;
	 @Excel(name = "交易额（北美洲）", orderNum = "11")
	 private BigDecimal tradeVolumeNAmerica;
	 @Excel(name = "交易额（南美洲）", orderNum = "12")
	 private BigDecimal tradeVolumeSAmerica;
	 @Excel(name = "交易额（中国）", orderNum = "13")
	 private BigDecimal tradeVolumeSChina;

    public GlobalEshopTradeData() {
    }

	
    public GlobalEshopTradeData(String tradeId, String eshopId, String eshopNm, String tradeMonth, BigDecimal tradeVolume) {
        this.tradeId = tradeId;
    	this.eshopId = eshopId;
        this.eshopNm = eshopNm;
        this.tradeDate = tradeMonth;
        this.tradeVolume = tradeVolume;
    }
    public GlobalEshopTradeData(String tradeId, String eshopId, String eshopNm, String tradeMonth, BigDecimal tradeVolume, BigDecimal tradeVolumeDeveloped, BigDecimal tradeVolumeDeveloping, BigDecimal tradeVolumeAsia, BigDecimal tradeVolumeEurope, BigDecimal tradeVolumeAfrica, BigDecimal tradeVolumeOceania, BigDecimal tradeVolumeNAmerica, BigDecimal tradeVolumeSAmerica, BigDecimal tradeVolumeSChina) {
       this.tradeId = tradeId;
       this.eshopId = eshopId;
       this.eshopNm = eshopNm;
       this.tradeDate = tradeMonth;
       this.tradeVolume = tradeVolume;
       this.tradeVolumeDeveloped = tradeVolumeDeveloped;
       this.tradeVolumeDeveloping = tradeVolumeDeveloping;
       this.tradeVolumeAsia = tradeVolumeAsia;
       this.tradeVolumeEurope = tradeVolumeEurope;
       this.tradeVolumeAfrica = tradeVolumeAfrica;
       this.tradeVolumeOceania = tradeVolumeOceania;
       this.tradeVolumeNAmerica = tradeVolumeNAmerica;
       this.tradeVolumeSAmerica = tradeVolumeSAmerica;
       this.tradeVolumeSChina = tradeVolumeSChina;
    }
   
     @Id 
  	 @GeneratedValue(generator = "uid")
  	 @GenericGenerator(name = "uid", strategy = "uuid")
     @Column(name="trade_id", unique=true, nullable=false, length=64)
     public String getTradeId() {
         return this.tradeId;
     }
     
     public void setTradeId(String tradeId) {
         this.tradeId = tradeId;
     }
    
    @Column(name="eshop_id", nullable=false, length=32)
    public String getEshopId() {
        return this.eshopId;
    }
    
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    
    @Column(name="eshop_nm", nullable=false, length=64)
    public String getEshopNm() {
        return this.eshopNm;
    }
    
    public void setEshopNm(String eshopNm) {
        this.eshopNm = eshopNm;
    }

    
    @Column(name="trade_date", nullable=false, length=7)
    public String getTradeDate() {
        return this.tradeDate;
    }
    
    public void setTradeDate(String tradeMonth) {
        this.tradeDate = tradeMonth;
    }

    
    @Column(name="trade_volume", nullable=false, precision=12)
    public BigDecimal getTradeVolume() {
        return this.tradeVolume;
    }
    
    public void setTradeVolume(BigDecimal tradeVolume) {
        this.tradeVolume = tradeVolume;
    }

    
    @Column(name="trade_volume_developed", precision=12)
    public BigDecimal getTradeVolumeDeveloped() {
        return this.tradeVolumeDeveloped;
    }
    
    public void setTradeVolumeDeveloped(BigDecimal tradeVolumeDeveloped) {
        this.tradeVolumeDeveloped = tradeVolumeDeveloped;
    }

    
    @Column(name="trade_volume_developing", precision=12)
    public BigDecimal getTradeVolumeDeveloping() {
        return this.tradeVolumeDeveloping;
    }
    
    public void setTradeVolumeDeveloping(BigDecimal tradeVolumeDeveloping) {
        this.tradeVolumeDeveloping = tradeVolumeDeveloping;
    }

    
    @Column(name="trade_volume_asia", precision=12)
    public BigDecimal getTradeVolumeAsia() {
        return this.tradeVolumeAsia;
    }
    
    public void setTradeVolumeAsia(BigDecimal tradeVolumeAsia) {
        this.tradeVolumeAsia = tradeVolumeAsia;
    }

    
    @Column(name="trade_volume_europe", precision=12)
    public BigDecimal getTradeVolumeEurope() {
        return this.tradeVolumeEurope;
    }
    
    public void setTradeVolumeEurope(BigDecimal tradeVolumeEurope) {
        this.tradeVolumeEurope = tradeVolumeEurope;
    }

    
    @Column(name="trade_volume_africa", precision=12)
    public BigDecimal getTradeVolumeAfrica() {
        return this.tradeVolumeAfrica;
    }
    
    public void setTradeVolumeAfrica(BigDecimal tradeVolumeAfrica) {
        this.tradeVolumeAfrica = tradeVolumeAfrica;
    }

    
    @Column(name="trade_volume_oceania", precision=12)
    public BigDecimal getTradeVolumeOceania() {
        return this.tradeVolumeOceania;
    }
    
    public void setTradeVolumeOceania(BigDecimal tradeVolumeOceania) {
        this.tradeVolumeOceania = tradeVolumeOceania;
    }

    
    @Column(name="trade_volume_n_america", precision=12)
    public BigDecimal getTradeVolumeNAmerica() {
        return this.tradeVolumeNAmerica;
    }
    
    public void setTradeVolumeNAmerica(BigDecimal tradeVolumeNAmerica) {
        this.tradeVolumeNAmerica = tradeVolumeNAmerica;
    }

    
    @Column(name="trade_volume_s_america", precision=12)
    public BigDecimal getTradeVolumeSAmerica() {
        return this.tradeVolumeSAmerica;
    }
    
    public void setTradeVolumeSAmerica(BigDecimal tradeVolumeSAmerica) {
        this.tradeVolumeSAmerica = tradeVolumeSAmerica;
    }

    
    @Column(name="trade_volume_s_china", precision=12)
    public BigDecimal getTradeVolumeSChina() {
        return this.tradeVolumeSChina;
    }
    
    public void setTradeVolumeSChina(BigDecimal tradeVolumeSChina) {
        this.tradeVolumeSChina = tradeVolumeSChina;
    }




}


