package com.example.demo.entity;
// Generated 2019-5-8 8:54:23 by Hibernate Tools 5.2.5.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GlobalEshopTradeData generated by hbm2java
 */
@Entity
@Table(name="global_eshop_trade_data"
)
public class GlobalEshopTradeData  implements java.io.Serializable {


     private String eshopId;
     private String eshopNm;
     private String tradeMonth;
     private BigDecimal tradeVolume;
     private BigDecimal tradeVolumeDeveloped;
     private BigDecimal tradeVolumeDeveloping;
     private BigDecimal tradeVolumeAsia;
     private BigDecimal tradeVolumeEurope;
     private BigDecimal tradeVolumeAfrica;
     private BigDecimal tradeVolumeOceania;
     private BigDecimal tradeVolumeNAmerica;
     private BigDecimal tradeVolumeSAmerica;
     private BigDecimal tradeVolumeSChina;

    public GlobalEshopTradeData() {
    }

	
    public GlobalEshopTradeData(String eshopId, String eshopNm, String tradeMonth, BigDecimal tradeVolume) {
        this.eshopId = eshopId;
        this.eshopNm = eshopNm;
        this.tradeMonth = tradeMonth;
        this.tradeVolume = tradeVolume;
    }
    public GlobalEshopTradeData(String eshopId, String eshopNm, String tradeMonth, BigDecimal tradeVolume, BigDecimal tradeVolumeDeveloped, BigDecimal tradeVolumeDeveloping, BigDecimal tradeVolumeAsia, BigDecimal tradeVolumeEurope, BigDecimal tradeVolumeAfrica, BigDecimal tradeVolumeOceania, BigDecimal tradeVolumeNAmerica, BigDecimal tradeVolumeSAmerica, BigDecimal tradeVolumeSChina) {
       this.eshopId = eshopId;
       this.eshopNm = eshopNm;
       this.tradeMonth = tradeMonth;
       this.tradeVolume = tradeVolume;
       this.tradeVolumeDeveloped = tradeVolumeDeveloped;
       this.tradeVolumeDeveloping = tradeVolumeDeveloping;
       this.tradeVolumeAsia = tradeVolumeAsia;
       this.tradeVolumeEurope = tradeVolumeEurope;
       this.tradeVolumeAfrica = tradeVolumeAfrica;
       this.tradeVolumeOceania = tradeVolumeOceania;
       this.tradeVolumeNAmerica = tradeVolumeNAmerica;
       this.tradeVolumeSAmerica = tradeVolumeSAmerica;
       this.tradeVolumeSChina = tradeVolumeSChina;
    }
   
     @Id 

    
    @Column(name="eshop_id", unique=true, nullable=false, length=32)
    public String getEshopId() {
        return this.eshopId;
    }
    
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    
    @Column(name="eshop_nm", nullable=false, length=64)
    public String getEshopNm() {
        return this.eshopNm;
    }
    
    public void setEshopNm(String eshopNm) {
        this.eshopNm = eshopNm;
    }

    
    @Column(name="trade_month", nullable=false, length=2)
    public String getTradeMonth() {
        return this.tradeMonth;
    }
    
    public void setTradeMonth(String tradeMonth) {
        this.tradeMonth = tradeMonth;
    }

    
    @Column(name="trade_volume", nullable=false, precision=12)
    public BigDecimal getTradeVolume() {
        return this.tradeVolume;
    }
    
    public void setTradeVolume(BigDecimal tradeVolume) {
        this.tradeVolume = tradeVolume;
    }

    
    @Column(name="trade_volume_developed", precision=12)
    public BigDecimal getTradeVolumeDeveloped() {
        return this.tradeVolumeDeveloped;
    }
    
    public void setTradeVolumeDeveloped(BigDecimal tradeVolumeDeveloped) {
        this.tradeVolumeDeveloped = tradeVolumeDeveloped;
    }

    
    @Column(name="trade_volume_developing", precision=12)
    public BigDecimal getTradeVolumeDeveloping() {
        return this.tradeVolumeDeveloping;
    }
    
    public void setTradeVolumeDeveloping(BigDecimal tradeVolumeDeveloping) {
        this.tradeVolumeDeveloping = tradeVolumeDeveloping;
    }

    
    @Column(name="trade_volume_asia", precision=12)
    public BigDecimal getTradeVolumeAsia() {
        return this.tradeVolumeAsia;
    }
    
    public void setTradeVolumeAsia(BigDecimal tradeVolumeAsia) {
        this.tradeVolumeAsia = tradeVolumeAsia;
    }

    
    @Column(name="trade_volume_europe", precision=12)
    public BigDecimal getTradeVolumeEurope() {
        return this.tradeVolumeEurope;
    }
    
    public void setTradeVolumeEurope(BigDecimal tradeVolumeEurope) {
        this.tradeVolumeEurope = tradeVolumeEurope;
    }

    
    @Column(name="trade_volume_africa", precision=12)
    public BigDecimal getTradeVolumeAfrica() {
        return this.tradeVolumeAfrica;
    }
    
    public void setTradeVolumeAfrica(BigDecimal tradeVolumeAfrica) {
        this.tradeVolumeAfrica = tradeVolumeAfrica;
    }

    
    @Column(name="trade_volume_oceania", precision=12)
    public BigDecimal getTradeVolumeOceania() {
        return this.tradeVolumeOceania;
    }
    
    public void setTradeVolumeOceania(BigDecimal tradeVolumeOceania) {
        this.tradeVolumeOceania = tradeVolumeOceania;
    }

    
    @Column(name="trade_volume_n_america", precision=12)
    public BigDecimal getTradeVolumeNAmerica() {
        return this.tradeVolumeNAmerica;
    }
    
    public void setTradeVolumeNAmerica(BigDecimal tradeVolumeNAmerica) {
        this.tradeVolumeNAmerica = tradeVolumeNAmerica;
    }

    
    @Column(name="trade_volume_s_america", precision=12)
    public BigDecimal getTradeVolumeSAmerica() {
        return this.tradeVolumeSAmerica;
    }
    
    public void setTradeVolumeSAmerica(BigDecimal tradeVolumeSAmerica) {
        this.tradeVolumeSAmerica = tradeVolumeSAmerica;
    }

    
    @Column(name="trade_volume_s_china", precision=12)
    public BigDecimal getTradeVolumeSChina() {
        return this.tradeVolumeSChina;
    }
    
    public void setTradeVolumeSChina(BigDecimal tradeVolumeSChina) {
        this.tradeVolumeSChina = tradeVolumeSChina;
    }




}


