package com.example.demo.entity;
// Generated 2019-5-8 8:54:23 by Hibernate Tools 5.2.5.Final


import java.time.LocalDate;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GlobalEshopInfo generated by hbm2java
 */
@Entity
@Table(name="global_eshop_info"
)
public class GlobalEshopInfo  implements java.io.Serializable {


     private String eshopId;
     private String eshopNm;
     private String countryNm;
     private String address;
     private LocalDate establishedDate;
     private String briefIntroduction;
     private String detailsIntroduction;
     private Boolean isMainEshop;

    public GlobalEshopInfo() {
    }

	
    public GlobalEshopInfo(String eshopId, String eshopNm, String countryNm) {
        this.eshopId = eshopId;
        this.eshopNm = eshopNm;
        this.countryNm = countryNm;
    }
    public GlobalEshopInfo(String eshopId, String eshopNm, String countryNm, String address, LocalDate establishedDate, String briefIntroduction, String detailsIntroduction, Boolean isMainEshop) {
       this.eshopId = eshopId;
       this.eshopNm = eshopNm;
       this.countryNm = countryNm;
       this.address = address;
       this.establishedDate = establishedDate;
       this.briefIntroduction = briefIntroduction;
       this.detailsIntroduction = detailsIntroduction;
       this.isMainEshop = isMainEshop;
    }
   
     @Id 

    
    @Column(name="eshop_id", unique=true, nullable=false, length=24)
    public String getEshopId() {
        return this.eshopId;
    }
    
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    
    @Column(name="eshop_nm", nullable=false, length=32)
    public String getEshopNm() {
        return this.eshopNm;
    }
    
    public void setEshopNm(String eshopNm) {
        this.eshopNm = eshopNm;
    }

    
    @Column(name="country_nm", nullable=false, length=32)
    public String getCountryNm() {
        return this.countryNm;
    }
    
    public void setCountryNm(String countryNm) {
        this.countryNm = countryNm;
    }

    
    @Column(name="address", length=64)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="established_date", length=13)
    public LocalDate getEstablishedDate() {
        return this.establishedDate;
    }
    
    public void setEstablishedDate(LocalDate establishedDate) {
        this.establishedDate = establishedDate;
    }

    
    @Column(name="brief_introduction", length=200)
    public String getBriefIntroduction() {
        return this.briefIntroduction;
    }
    
    public void setBriefIntroduction(String briefIntroduction) {
        this.briefIntroduction = briefIntroduction;
    }

    
    @Column(name="details_introduction", length=200)
    public String getDetailsIntroduction() {
        return this.detailsIntroduction;
    }
    
    public void setDetailsIntroduction(String detailsIntroduction) {
        this.detailsIntroduction = detailsIntroduction;
    }

    
    @Column(name="is_main_eshop")
    public Boolean getIsMainEshop() {
        return this.isMainEshop;
    }
    
    public void setIsMainEshop(Boolean isMainEshop) {
        this.isMainEshop = isMainEshop;
    }




}


