package com.example.demo.entity;
// Generated 2019-5-8 8:54:23 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GlobalEshopUsersData generated by hbm2java
 */
@Entity
@Table(name="global_eshop_users_data"
)
public class GlobalEshopUsersData  implements java.io.Serializable {


     private String eshopId;
     private String eshopNm;
     private Long userNum;
     private Long uerNumDevelop;
     private Long userNumDeveloping;

    public GlobalEshopUsersData() {
    }

	
    public GlobalEshopUsersData(String eshopId, String eshopNm) {
        this.eshopId = eshopId;
        this.eshopNm = eshopNm;
    }
    public GlobalEshopUsersData(String eshopId, String eshopNm, Long userNum, Long uerNumDevelop, Long userNumDeveloping) {
       this.eshopId = eshopId;
       this.eshopNm = eshopNm;
       this.userNum = userNum;
       this.uerNumDevelop = uerNumDevelop;
       this.userNumDeveloping = userNumDeveloping;
    }
   
     @Id 

    
    @Column(name="eshop_id", unique=true, nullable=false, length=24)
    public String getEshopId() {
        return this.eshopId;
    }
    
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    
    @Column(name="eshop_nm", nullable=false, length=64)
    public String getEshopNm() {
        return this.eshopNm;
    }
    
    public void setEshopNm(String eshopNm) {
        this.eshopNm = eshopNm;
    }

    
    @Column(name="user_num", precision=12, scale=0)
    public Long getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(Long userNum) {
        this.userNum = userNum;
    }

    
    @Column(name="uer_num_develop", precision=12, scale=0)
    public Long getUerNumDevelop() {
        return this.uerNumDevelop;
    }
    
    public void setUerNumDevelop(Long uerNumDevelop) {
        this.uerNumDevelop = uerNumDevelop;
    }

    
    @Column(name="user_num_developing", precision=12, scale=0)
    public Long getUserNumDeveloping() {
        return this.userNumDeveloping;
    }
    
    public void setUserNumDeveloping(Long userNumDeveloping) {
        this.userNumDeveloping = userNumDeveloping;
    }




}


