package com.example.demo.entity;
// Generated 2019-5-13 17:48:45 by Hibernate Tools 5.2.5.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import cn.afterturn.easypoi.excel.annotation.Excel;

/**
 * GlobalEshopOverseasRepo generated by hbm2java
 */
@Entity
@Table(name="global_eshop_overseas_repo"
)
public class GlobalEshopOverseasRepo  implements java.io.Serializable {

	 
	 @Excel(name = "仓库编号(请勿修改)", orderNum = "0")
     private String repoId;
	 @Excel(name = "电商ID", orderNum = "1")
	 private String eshopId;
	 @Excel(name = "电商名称", orderNum = "2")
	 private String eshopNm;
	 @Excel(name = "海外仓", orderNum = "3")
	 private String overseasRepo;
	 @Excel(name = "地理位置(经度)", orderNum = "4")
	 private BigDecimal repoLocationX;
	 @Excel(name = "地理位置(纬度)", orderNum = "5")
	 private BigDecimal repoLocationY;
	 @Excel(name = "容量", orderNum = "6")
	 private Long capacity;
	 @Excel(name = "库存", orderNum = "7")
	 private Long totalStock;
	 @Excel(name = "可用库存", orderNum = "8")
	 private Long useabelStock;

    public GlobalEshopOverseasRepo() {
    }

	
    public GlobalEshopOverseasRepo(String repoId, String eshopId, String eshopNm, String overseasRepo) {
        this.repoId = repoId;
        this.eshopId = eshopId;
        this.eshopNm = eshopNm;
        this.overseasRepo = overseasRepo;
    }
    public GlobalEshopOverseasRepo(String repoId, String eshopId, String eshopNm, String overseasRepo, BigDecimal repoLocationX, BigDecimal repoLocationY, Long capacity, Long totalStock, Long useabelStock) {
       this.repoId = repoId;
       this.eshopId = eshopId;
       this.eshopNm = eshopNm;
       this.overseasRepo = overseasRepo;
       this.repoLocationX = repoLocationX;
       this.repoLocationY = repoLocationY;
       this.capacity = capacity;
       this.totalStock = totalStock;
       this.useabelStock = useabelStock;
    }
   
     @Id 
  	@GeneratedValue(generator = "uid")
  	@GenericGenerator(name = "uid", strategy = "uuid")
    @Column(name="repo_id", unique=true, nullable=false, length=64)
    public String getRepoId() {
        return this.repoId;
    }
    
    public void setRepoId(String repoId) {
        this.repoId = repoId;
    }

    
    @Column(name="eshop_id", nullable=false, length=32)
    public String getEshopId() {
        return this.eshopId;
    }
    
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    
    @Column(name="eshop_nm", nullable=false, length=32)
    public String getEshopNm() {
        return this.eshopNm;
    }
    
    public void setEshopNm(String eshopNm) {
        this.eshopNm = eshopNm;
    }

    
    @Column(name="overseas_repo", nullable=false, length=32)
    public String getOverseasRepo() {
        return this.overseasRepo;
    }
    
    public void setOverseasRepo(String overseasRepo) {
        this.overseasRepo = overseasRepo;
    }

    
    @Column(name="repo_location_x", precision=6, scale=3)
    public BigDecimal getRepoLocationX() {
        return this.repoLocationX;
    }
    
    public void setRepoLocationX(BigDecimal repoLocationX) {
        this.repoLocationX = repoLocationX;
    }

    
    @Column(name="repo_location_y", precision=6, scale=3)
    public BigDecimal getRepoLocationY() {
        return this.repoLocationY;
    }
    
    public void setRepoLocationY(BigDecimal repoLocationY) {
        this.repoLocationY = repoLocationY;
    }

    
    @Column(name="capacity", precision=12, scale=0)
    public Long getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Long capacity) {
        this.capacity = capacity;
    }

    
    @Column(name="total_stock", precision=12, scale=0)
    public Long getTotalStock() {
        return this.totalStock;
    }
    
    public void setTotalStock(Long totalStock) {
        this.totalStock = totalStock;
    }

    
    @Column(name="useabel_stock", precision=12, scale=0)
    public Long getUseabelStock() {
        return this.useabelStock;
    }
    
    public void setUseabelStock(Long useabelStock) {
        this.useabelStock = useabelStock;
    }




}


