package com.example.demo.entity;
// Generated 2019-5-8 8:54:23 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GlobalCountryInfo generated by hbm2java
 */
@Entity
@Table(name="global_country_info"
)
public class GlobalCountryInfo  implements java.io.Serializable {


     private String countryId;
     private String countryNm;
     private String continents;
     private String continentsArea;
     private String countryType;

    public GlobalCountryInfo() {
    }

    public GlobalCountryInfo(String countryId, String countryNm, String continents, String continentsArea, String countryType) {
       this.countryId = countryId;
       this.countryNm = countryNm;
       this.continents = continents;
       this.continentsArea = continentsArea;
       this.countryType = countryType;
    }
   
     @Id 

    
    @Column(name="country_id", unique=true, nullable=false, length=32)
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="country_nm", nullable=false, length=64)
    public String getCountryNm() {
        return this.countryNm;
    }
    
    public void setCountryNm(String countryNm) {
        this.countryNm = countryNm;
    }

    
    @Column(name="continents", nullable=false, length=12)
    public String getContinents() {
        return this.continents;
    }
    
    public void setContinents(String continents) {
        this.continents = continents;
    }

    
    @Column(name="continents_area", nullable=false, length=24)
    public String getContinentsArea() {
        return this.continentsArea;
    }
    
    public void setContinentsArea(String continentsArea) {
        this.continentsArea = continentsArea;
    }

    
    @Column(name="country_type", nullable=false, length=24)
    public String getCountryType() {
        return this.countryType;
    }
    
    public void setCountryType(String countryType) {
        this.countryType = countryType;
    }




}


